### ISSUE TITLE
Return Nothing

### ISSUE THREAD

**Issue by Yizhang-Li** [BuffetCode/edinet_xbrl#10]
I get nothing when I run the following code.

ticker = "8316"
xbrl_downloader.download_by_ticker(ticker, target_dir)

**Comment by knari6** [comment]
I got same situation.
I checked download_by_ticker and it returns <Response[404]>.

**Comment by shoe116** [comment]
ufocatcher api is closed, so https://github.com/BuffettCode/edinet_xbrl/blob/master/edinet_xbrl/ufocatcher_util.py is not working.
