### ISSUE TITLE
it can work for only current 3 years.

### ISSUE THREAD

**Issue by pakapon-peace** [BuffetCode/edinet_xbrl#2]
It can't be get some xbrl, for example, "jpfr-asr-E00457-000-2009-03-31-01-2009-06-26.xbrl" that is a report of 2897:Nissin (from H20.4.1 to H21.3.31), and/or "jpcrp030000-asr-001_E00457-000_2014-03-31_01_2014-06-26.xbrl" that is a report of 2897:Nissin (from H25.4.1 to H26.3.31).

**Comment by shoe116** [comment]
@pakapon-peace thx, i'll check my codes...

**Comment by KaixiRen31** [comment]
I experience the same issue. No xbrl older than 3 years back is downloaded.

**Comment by shoe116** [comment]
@pakapon-peace @KaixiRen31  this module using [ufocatch api](https://resource.ufocatch.com/). and the api support last 3 years only.
